import React from "react";
import Head from "next/head";
import Link from "next/link";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>ChockoCoin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-dark h-100vh d-flex flex-column justify-content-center align-items-center flex-wrap">
        <div className="w-100 mb-5">
          <h1 className="text-center text-white">ChockoCoin</h1>
        </div>
        <div className="d-flex w-100 justify-content-around align-items-center mt-5">
          <Link href="/login" passHref>
            <a className="btn btn-success w-25">Login</a>
          </Link>
          <Link href="#">
            <a href="" className="btn btn-primary w-25">
              Cadastrar
            </a>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
