import React from "react";
import Head from "next/head";
import { Card, Form } from "react-bootstrap";
import { useForm, FormProvider, useFormContext } from "react-hook-form";

const Login: React.FC = () => {
  return (
    <>
      <Form.Group>
        <Form.Label>Email</Form.Label>
        <Form.Control type="email" placeholder="Digite seu email" />
      </Form.Group>

      <Form.Group>
        <Form.Label>Senha</Form.Label>
        <Form.Control type="password" />
      </Form.Group>
    </>
  );
};

const Home: React.FC = () => {
  const methods = useFormContext();

  return (
    <>
      <Head>
        <title>ChockoCoin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-dark h-100vh d-flex flex-column justify-content-center">
        <Card>
          <Card.Header className="text-center">ChockoCoin</Card.Header>
          <Card.Body>
            <FormProvider {...methods}>
              <Form>
                <Login />
              </Form>
            </FormProvider>
          </Card.Body>
        </Card>
      </main>
    </>
  );
};

export default Home;
